name: "Check cpp-dev"
on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'cpp-dev.dockerfile'
      - 'Makefile'
  pull_request:
    paths:
      - 'cpp-dev.dockerfile'
      - 'Makefile'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build cpp-dev
        env:
          PLATFORMS: linux/amd64,linux/arm64
          DOCKER_BUILD: docker buildx build
        run: make cpp-dev
        
